### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by oxodao** [knarkzel/raise#1]
Hi!
Thanks for this tool, it works as intended and it eases my migration from i3.
Do you have any plans to publish it to the archlinux's AUR ? I'd like to install it directly in my ansible script without having to resort to manual install. It would be neat that the executable would be moved directly to `/usr/local/bin/raise` instead of `~/.cargo/bin/raise`

Edit:

Here's the how-to, it's pretty simple: https://wiki.archlinux.org/title/AUR_submission_guidelines
If you want some inspiration for a simple package that use a release binary I've made one for my `metaprint` software: https://github.com/oxodao/metaprint/blob/master/packaging/arch/PKGBUILD
It should be pretty similar as Rust is producing a one-executable software just as Go 

Thanks!

**Comment by lambdachad** [comment]
I don't have any plans to add it to the AUR but feel free to do so! :smile:

**Comment by lambdachad** [comment]
Should be quite simple because it's a static binary, doesn't have any dependencies for running.

**Comment by lambdachad** [comment]
Closing this because it lacks motivation.

**Comment by oxodao** [comment]
Sorry yes, I forgot to tell you, but I no longer need it as I went back to X11 I'm no longer using Hyprland
