### ISSUE TITLE
difficulties setting up my flake.nix

### ISSUE THREAD

**Issue by ehula** [knarkzel/raise#3]
I have installed this by adding `github:knarkzel/raise` to my flake.nix.

I also have this is my flake.nix (is this correct?):

```
...
modules = [
    raise.defaultPackage.x86_64-linux
...
```

but when trying to install in home-manager, I get the following error:

```
error: The option `RUSTC' does not exist. Definition values:
```

**Comment by ehula** [comment]
I managed to get it working, so it is not a problem with the package, but I am not very familiar with flakes.

What is the preferred way to install this package using a flake? I am running home-manager as well.

**Comment by lambdachad** [comment]
I'll add example to README, I do it like this:
```nix
inputs = {
  nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  raise.url = "github:knarkzel/raise";
};
```
Then add the package, such as `environment.systemPackages = [raise.defaultPackage.x86_64-linux]`
